#!/bin/sh /etc/rc.common
USE_PROCD=1
START=99
NAME="ech-workers"
BIN="/usr/bin/ech-workers"
start_service() {
    config_load "$NAME"
    local enabled server_addr listen_addr
    config_get enabled "config" "enabled" "0"
    [ "$enabled" = "1" ] || return 0
    config_get server_addr "config" "server_addr" ""
    config_get listen_addr "config" "listen_addr" "0.0.0.0:30001"
    procd_open_instance "$NAME"
    procd_set_param command "$BIN" -f "$server_addr" -l "$listen_addr"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
